### ISSUE TITLE
Laravel 5 Issues

### ISSUE THREAD

**Issue by darylldoyle** [mandreoli/api-proxy-laravel#6]
This is currently unusable on L5. When running the `php artisan config:publish andreoli/api-proxy-laravel` command, I get the following error:

``` shell
➜  project git:(oauth) ✗ php artisan config:publish andreoli/api-proxy-laravel
PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::error() in /home/vagrant/Code/project/vendor/andreoli/api-proxy-laravel/src/Andreoli/ApiProxy/ApiProxyServiceProvider.php on line 75
```

This is because L5 removed the `Application::error()` method.

**Comment by thinkingmik** [comment]
Yes, currently this package is not available for laravel 5. Sorry

**Comment by csprocket777** [comment]
Is there any update on this project to bring it to Laravel 5? I'm really in need of this and am not finding any other solution.

**Comment by Cellcote** [comment]
I got this to work with some hacks on Laravel 5, I'll try to upload it tonight if anyone is still interested.

**Comment by 4success** [comment]
We are interested!

**Comment by csprocket777** [comment]
YES PLEASE!!!

**Comment by Cellcote** [comment]
This should work: https://github.com/Cellcote/laravel-proxify/tree/master
Note one change I made: Instead of sending the uri for the proxy as a parameter, you can append it after the proxy (e.g. a call to proxify/localhost/oauth/access_token will make the proxy will get the token from localhost/oauth/access_token).
